import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';
import { mountMotions } from './motion.js';

// Modo local permite experimentar o catálogo e o painel sem autenticação real.
// Ao configurar Supabase, todos os writes usam RLS e só admins autorizados podem editar.
const hasBackend = Boolean(SUPABASE_URL && SUPABASE_ANON_KEY);
let supa = null, user = null, isAdmin = false;
const BASE = 'https://intactoz-underground.contamateusfortnite.chatgpt.site/images/';
const KACE = 'https://www.kacewear.com.br/blogs/conteudo/sidoka-e-intactoz-x-kace-collab-envelope-traz-novas-roupas-e-acessorios';
const editorial = {
  hero: 'https://cdn.shopify.com/s/files/1/0222/0104/0992/files/FOTO_1_-_Collab_Sidoka_e_Intactoz_x_Kace_-_Jaqueta_e_Moletom_Sidoka_c5fea28f-45af-4b7e-a72b-8c7eb173cd30.png?v=1617293060',
  first: 'https://cdn.shopify.com/s/files/1/0222/0104/0992/files/FOTO_1_-_Collab_Sidoka_e_Intactoz_x_Kace_-_Jaqueta_e_Moletom_Sidoka_c5fea28f-45af-4b7e-a72b-8c7eb173cd30.png?v=1617293060',
  second: 'https://cdn.shopify.com/s/files/1/0222/0104/0992/files/FOTO_5_-_Collab_Sidoka_e_Intactoz_x_Kace_-_Camiseta_Blusa_e_Moletom_Sidoka_58526ecf-c2c8-46d5-b195-5a9ca67ce790.png?v=1617293387'
};
const initialProducts = [
{id:'bone',name:'Boné Sidoka Se Vc N Ama Preto',short_name:'SE VC N AMA / CAP',price_cents:13990,category:'Acessórios',collection:'Se Vc N Ama',color:'PRETO',description:'Boné preto da coleção Se Vc N Ama, Sidoka e intactoz. Veja acabamento e disponibilidade na loja original.',material:'Composição a confirmar',images:[BASE+'bone-1.webp',BASE+'bone-2.webp'],url:'https://intactoz.com.br/products/bone-sidoka-se-vc-n-ama-preto'},
{id:'chroma',name:'Camiseta Sidoka Chroma Preta',short_name:'CHROMA',price_cents:14990,category:'Camisetas',collection:'Chroma',color:'PRETO',description:'Camiseta preta da linha Sidoka Chroma.',material:'Composição a confirmar',images:[BASE+'chroma-1.webp',BASE+'chroma-2.webp'],url:'https://intactoz.com.br/products/camiseta-sidoka-chroma-preta'},
{id:'quadro',name:'Moletom Canguru Preto Quadro Sidoka',short_name:'QUADRO',price_cents:38990,category:'Moletons',collection:'Quadro',color:'PRETO',description:'Modelo canguru com estampa Quadro e símbolo Futuruz refletivo.',material:'50% algodão / 50% poliéster',images:[BASE+'quadro-1.webp',BASE+'quadro-2.webp'],url:'https://intactoz.com.br/products/moletom-canguru-preto-quadro-sidoka'},
{id:'ama',name:'Camiseta Sidoka Se Vc N Ama Preta',short_name:'SE VC N AMA',price_cents:14990,category:'Camisetas',collection:'Se Vc N Ama',color:'PRETO',description:'Camiseta preta da coleção Se Vc N Ama.',material:'Composição a confirmar',images:[BASE+'ama-1.webp',BASE+'ama-2.webp'],url:'https://intactoz.com.br/products/camiseta-sidoka-se-vc-n-ama-preta'}
];
const DEFAULT_CATEGORIES = ['Acessórios','Camisetas','Moletons'];
const DEFAULT_COLLECTIONS = ['Chroma','Quadro','Se Vc N Ama'];
const h = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const price = cents => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(cents)||0)/100);
const onlyHTTP = url => /^https:\/\/[^\s]+$/i.test(url||'') ? url : '';
const fallback = title => {const t=h(String(title||'INTACTOZ').slice(0,35));return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 700 900"><rect width="700" height="900" fill="#eae9e6"/><g fill="#111"><path d="M180 290L290 230L410 230L520 290L600 440L515 490L465 405L465 750L235 750L235 405L185 490L100 440Z" opacity=".95"/></g><text x="350" y="820" fill="#111" text-anchor="middle" font-size="28" font-family="Arial" font-weight="bold">${t}</text></svg>`)};
const productImg = p => p.images?.[0] || fallback(p.short_name);
const $ = (s,p=document) => p.querySelector(s);
const $$ = (s,p=document) => [...p.querySelectorAll(s)];
const main = $('#main-content');
const data = {products:[],categories:[],collections:[]};
const app = {filter:'Todas',collection:'Todas',adminTab:'products',adminQuery:'',authMode:'login',modalReturnFocus:null};
let toastTimer;
function toast(message){const el=$('#toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,4500)}
function safeJson(str,fallback){try{return JSON.parse(str)||fallback}catch{return fallback}}
function loadLocal(){const local=safeJson(localStorage.getItem('intactoz-demo-v2'),null);Object.assign(data,local||{products:structuredClone(initialProducts),categories:[...DEFAULT_CATEGORIES],collections:[...DEFAULT_COLLECTIONS]})}
function saveLocal(){try{localStorage.setItem('intactoz-demo-v2',JSON.stringify(data))}catch{toast('O armazenamento deste navegador está cheio. Use imagens menores ou conecte o Supabase.')}}
async function setupBackend(){if(!hasBackend){loadLocal();return}try{const m=await import('https://esm.sh/@supabase/supabase-js@2.57.4');supa=m.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);const {data:{user:u}}=await supa.auth.getUser();user=u;await refreshAdmin();await refreshData();supa.auth.onAuthStateChange(async (_,session)=>{user=session?.user||null;await refreshAdmin();if(location.hash.startsWith('#/conta')||location.hash.startsWith('#/adm'))route()})}catch(err){console.error(err);data.products=structuredClone(initialProducts);data.categories=[...DEFAULT_CATEGORIES];data.collections=[...DEFAULT_COLLECTIONS];toast('Servidor indisponível: catálogo de referência em modo leitura.')}}
async function refreshAdmin(){if(!supa||!user){isAdmin=false;return}try{const {data:d,error}=await supa.rpc('is_intactoz_admin');if(error)throw error;isAdmin=Boolean(d)}catch{isAdmin=false}}
async function refreshData(){if(!supa)return;const results=await Promise.all([supa.from('products').select('*').order('created_at',{ascending:true}),supa.from('categories').select('name').order('name'),supa.from('collections').select('name').order('name')]);if(results.some(x=>x.error))throw results.find(x=>x.error).error;data.products=results[0].data||[];data.categories=results[1].data.map(x=>x.name);data.collections=results[2].data.map(x=>x.name)}
function image(tag,src,alt,extra=''){return `<img ${extra} src="${h(src)}" alt="${h(alt)}" loading="lazy" data-fallback="${h(alt)}">`}
function hero(){return `<section class="hero" id="inicio">${image('',editorial.hero,'Editorial Intactoz × KACE','class="hero-image greyphoto" fetchpriority="high"')}<div class="hero-inner"><p class="eyebrow"><em>✚</em> &nbsp; SIDOKA × INTACTOZ.</p><h1 class="display">O UNDER<br>TEM <span class="red">NOME.</span></h1><p class="hero-copy">A rua veste a própria voz.<br>Conheça o universo intactoz.</p><div class="hero-actions"><a class="btn" href="#/pecas">EXPLORAR AS PEÇAS</a><a class="text-link" href="#/editorial">VER O EDITORIAL</a></div></div><span class="hero-side">INTACTOZ. — CULTURA DE RUA</span><div class="hero-bottom"><span>BELO HORIZONTE / BRASIL</span><span>STREETWEAR. MÚSICA. IDENTIDADE.</span><span>SCROLL PARA EXPLORAR</span></div></section><div class="ticker" aria-label="INTACTOZ. SEM PEDIR LICENÇA. UNDERGROUND CULTURE"><div class="ticker-track" aria-hidden="true"><span class="ticker-copy">INTACTOZ. <em>✳</em> SEM PEDIR LICENÇA <em>✳</em> UNDERGROUND CULTURE <em>✳</em> INTACTOZ. <em>✳</em> SEM PEDIR LICENÇA <em>✳</em> UNDERGROUND CULTURE <em>✳</em> INTACTOZ. <em>✳</em> SEM PEDIR LICENÇA <em>✳</em> UNDERGROUND CULTURE <em>✳</em> </span><span class="ticker-copy">INTACTOZ. <em>✳</em> SEM PEDIR LICENÇA <em>✳</em> UNDERGROUND CULTURE <em>✳</em> INTACTOZ. <em>✳</em> SEM PEDIR LICENÇA <em>✳</em> UNDERGROUND CULTURE <em>✳</em> INTACTOZ. <em>✳</em> SEM PEDIR LICENÇA <em>✳</em> UNDERGROUND CULTURE <em>✳</em> </span></div></div>`}
function productCard(p,i){return `<article class="product"><button class="product-image" data-detail="${h(p.id)}" aria-label="Ver ${h(p.name)}">${image('',productImg(p),p.name,'class="greyphoto"')}<span class="index">[ ${String(i+1).padStart(2,'0')} ]</span><span class="plus">+</span></button><div class="product-meta">${h(p.category)} / ${h(p.color||'PRETO')}</div><h3>${h(p.short_name)}</h3><p class="price">${price(p.price_cents)}</p><button class="product-view" data-detail="${h(p.id)}">VER PEÇA ↗</button></article>`}
function catalog(){const categories=['Todas',...data.categories];const filtered=data.products.filter(p=>(app.filter==='Todas'||p.category===app.filter)&&(app.collection==='Todas'||p.collection===app.collection));return `<section class="section" id="pecas"><div class="section-head"><div><p class="eyebrow"><em>[ 01 ]</em> / GUARDA-ROUPA DA CENA</p><h2 class="display">VISTA SUA FREQUÊNCIA.</h2></div><p>Camisetas, moletons e acessórios.<br>A estética de Sidoka fora dos palcos.</p></div><div class="category-tabs" role="group" aria-label="Filtrar por categoria">${categories.map(c=>`<button class="tab ${app.filter===c?'active':''}" data-category="${h(c)}" aria-pressed="${app.filter===c}">${c==='Todas'?'Todas as peças':h(c)}</button>`).join('')}</div><div class="filters-bottom"><span class="count">${filtered.length} PEÇA${filtered.length===1?'':'S'}</span><label class="filter-select">COLEÇÃO<select id="collection-filter"><option value="Todas">Todas as coleções</option>${data.collections.map(c=>`<option value="${h(c)}" ${app.collection===c?'selected':''}>${h(c)}</option>`).join('')}</select></label></div><div class="product-grid">${filtered.map(productCard).join('')||'<div class="empty">Nenhuma peça encontrada.</div>'}</div><div class="catalog-bottom"><span>Explore cada peça para ver descrição, material e fotos.</span><a class="text-link" href="#/conta">ENTRAR NA MINHA CONTA</a></div></section>`}
function editorialSection(){return `<section id="editorial" class="section editorial"><div class="editorial-head"><div><p class="eyebrow"><em>[ 02 ]</em> / ARQUIVO VISUAL</p><h2 class="display">A CENA<br>EM <span class="red">QUADRO.</span></h2></div><aside><span class="eyebrow red">ENVELOPE / 2021</span><p>Sidoka, intactoz. e KACE.<br>Uma colaboração que leva a identidade do artista para as peças e para a rua.</p><a class="text-link" href="${KACE}" target="_blank" rel="noopener noreferrer">CONHECER A COLLAB ↗</a></aside></div><div class="editorial-grid"><div><div class="editorial-image">${image('',editorial.first,'Editorial da coleção Envelope','class="greyphoto"')}</div><div class="frame">FRAME 01 / ENVELOPE</div></div><div><h3 class="outline display">SEM<br>FILTRO.</h3><div class="editorial-image alt">${image('',editorial.second,'Sidoka na coleção Envelope','class="greyphoto"')}</div><div class="frame">FRAME 02 / SIDOKA</div></div></div><p class="small">Editorial Envelope — fotografia: Conin. <a class="text-link" href="${KACE}" target="_blank" rel="noopener noreferrer">Ver créditos</a></p></section>`}
function universe(){return `<section id="universo" class="universe"><div><span class="eyebrow">[ 03 ] / INTACTOZ. POR INTEIRO</span><div class="universe-icon">✳</div></div><div><h2 class="display">MAIS QUE ROUPA.<br><span class="outlined">UMA FORMA</span><br>DE ESTAR NA CENA.</h2><div class="universe-bottom"><p>Da música para o que você veste. A intactoz. traduz o universo de Sidoka em peças com identidade própria — para quem vive a cultura, dentro e fora dos palcos.</p><a href="#/conta" class="btn">ENTRAR NO UNIVERSO ↗</a></div></div></section>`}
function homePage(){return hero()+catalog()+editorialSection()+universe()}
function accountPage(){const logged=Boolean(user);return `<div class="page"><div class="account-grid"><div class="account-left"><p class="eyebrow red">INTACTOZ. / SUA CONTA</p><h1 class="display">A CENA<br>COMEÇA<br><span class="red">COM VOCÊ.</span></h1><p>Seu acesso ao universo intactoz.<br>Entre ou crie sua conta para fazer parte.</p><div class="login-image">${image('','./assets/sidoka-login.jpg','Sidoka usando moletom preto e luvas rosas','class="greyphoto"')}</div></div><section class="box" aria-label="Minha conta">${!hasBackend?`<p class="eyebrow red">DEMONSTRAÇÃO / NÃO CONECTADO</p><h3>ÁREA DE CONTA</h3><p class="muted">A página de conta está preparada para login real por e-mail usando Supabase. É necessário configurar um banco do Intactoz antes de receber cadastros.</p><a class="btn" href="#/pecas">EXPLORAR AS PEÇAS</a>`:logged?`<div class="red">♙ VOCÊ ESTÁ NA CENA</div><h3>Salve!</h3><p class="auth-logged">${h(user.user_metadata?.full_name||user.email||'')}</p><label class="label">E-mail</label><p>${h(user.email)}</p><a href="#/pecas" class="btn">EXPLORAR AS PEÇAS</a>${isAdmin?'<p><a href="#/adm" class="text-link">ACESSAR ADMINISTRAÇÃO</a></p>':''}<p><button class="btn secondary" id="logout">SAIR DA CONTA</button></p>`:`<p class="eyebrow red">FAÇA PARTE DA CENA</p><h3>${app.authMode==='login'?'ENTRAR':'CRIAR CONTA'}</h3><div class="auth-tabs"><button data-auth="login" class="${app.authMode==='login'?'active':''}">ENTRAR</button><button data-auth="register" class="${app.authMode==='register'?'active':''}">CRIAR CONTA</button></div><form id="auth-form">${app.authMode==='register'?'<label class="label" for="auth-name">Nome completo</label><input id="auth-name" class="field" name="name" autocomplete="name" minlength="2" maxlength="120" required>':''}<label class="label" for="auth-email">E-mail</label><input class="field" name="email" type="email" id="auth-email" autocomplete="email" required><label class="label" for="auth-password">Senha</label><input class="field" name="password" type="password" id="auth-password" minlength="8" autocomplete="${app.authMode==='login'?'current-password':'new-password'}" required><button class="btn" type="submit">${app.authMode==='login'?'ENTRAR':'CRIAR CONTA'}</button></form><p class="form-feedback" id="auth-status" aria-live="polite"></p>${app.authMode==='login'?'<button class="text-link" id="reset-password">ESQUECI MINHA SENHA</button>':''}`}</section></div></div>`}
function lockedAdmin(){return `<div class="page"><div class="admin-locked"><div><span class="eyebrow red">⛨ &nbsp; ACESSO RESTRITO</span><h2 class="display">NOS BASTIDORES<br>DA CENA.</h2><p>Entre com uma conta autorizada para gerenciar os produtos, preços, imagens, categorias e coleções.</p></div><section class="box"><h3>LOGIN ADMINISTRADOR</h3>${!hasBackend?'<div class="admin-notice">Ainda não existe backend conectado. Você pode testar o painel somente no modo local de demonstração.</div><button id="open-demo-admin" class="btn">ABRIR PAINEL DE DEMONSTRAÇÃO</button>':user?`<p class="muted">Sua conta não possui autorização de administrador.</p><a href="#/conta" class="btn">MINHA CONTA</a>`:`<p class="muted">Entre com seu e-mail e senha primeiro.</p><a href="#/conta" class="btn">ENTRAR NA MINHA CONTA</a>`}</section></div></div>`}
function adminPage(){if(hasBackend&&!isAdmin)return lockedAdmin();if(!hasBackend&&!app.demoAdmin)return lockedAdmin();const tabs=[['products','Produtos'],['categories','Categorias'],['collections','Coleções']];return `<section class="page admin"><div class="page-header"><div><span class="eyebrow red">INTACTOZ. / ADMIN</span><h1 class="display">CONTROLE DO DROP.</h1><span class="muted">${hasBackend?h(user?.email||''):'DEMONSTRAÇÃO LOCAL'}</span></div><a href="#/" class="text-link">VER O SITE ↗</a></div>${!hasBackend?'<div class="admin-notice"><b>Modo demonstração:</b> alterações ficam somente neste navegador. Não há controle de acesso nem banco de dados online. Não use este modo como painel público em produção.</div>':''}<div class="stat-row"><div class="stat"><span>Produtos</span><strong>${data.products.length}</strong></div><div class="stat"><span>Categorias</span><strong>${data.categories.length}</strong></div><div class="stat"><span>Coleções</span><strong>${data.collections.length}</strong></div></div><div class="admin-tabs">${tabs.map(([id,name])=>`<button class="${app.adminTab===id?'active':''}" data-admin-tab="${id}" aria-pressed="${app.adminTab===id}">${name}</button>`).join('')}<button class="btn" id="add-new">+ ${app.adminTab==='products'?'ADICIONAR PRODUTO':app.adminTab==='categories'?'CRIAR CATEGORIA':'CRIAR COLEÇÃO'}</button></div><input id="admin-search" class="field search" aria-label="Buscar no painel" placeholder="Buscar produto, categoria ou coleção" value="${h(app.adminQuery)}"><div id="admin-list">${adminList()}</div></section>`}
function adminList(){const q=app.adminQuery.toLowerCase();if(app.adminTab==='products'){const ps=data.products.filter(p=>(p.name+' '+p.category+' '+p.collection).toLowerCase().includes(q));return `<div class="admin-list"><div class="admin-tablehead"><span>Produto</span><span>Preço</span><span>Categoria</span><span>Coleção</span><span>Ações</span></div>${ps.map(p=>`<div class="admin-item"><div class="admin-product">${image('',productImg(p),p.name)}<div><span>${h(p.name)}</span><small>${p.images?.length||0} FOTOS · ${h(p.color||'PRETO')}</small></div></div><span>${price(p.price_cents)}</span><span>${h(p.category)}</span><span>${h(p.collection)}</span><div class="action-group"><button data-edit-product="${h(p.id)}" aria-label="Editar ${h(p.name)}">✎</button><button data-remove-product="${h(p.id)}" aria-label="Excluir ${h(p.name)}">▤</button></div></div>`).join('')||'<div class="empty">Nenhum produto encontrado.</div>'}</div>`}const arr=(app.adminTab==='categories'?data.categories:data.collections).filter(x=>x.toLowerCase().includes(q));return `<div class="tax-grid">${arr.map(name=>`<div class="tax-card"><span class="eyebrow">${app.adminTab==='categories'?'CATEGORIA':'COLEÇÃO'}</span><h3 class="display">${h(name)}</h3><div class="muted">${data.products.filter(p=>(app.adminTab==='categories'?p.category:p.collection)===name).length} produtos</div><div class="actions"><button class="btn secondary" data-edit-tax="${h(name)}">✎ EDITAR</button><button class="btn secondary" data-remove-tax="${h(name)}" aria-label="Excluir ${h(name)}">▤</button></div></div>`).join('')||'<div class="empty">Nenhum item encontrado.</div>'}</div>`}
function modal(html){const overlay=$('#modal');app.modalReturnFocus=document.activeElement;$('#modal-content').innerHTML=`<button class="modal-close" type="button" data-close aria-label="Fechar">×</button>${html}`;overlay.hidden=false;document.body.classList.add('modal-open');$('#modal-content').focus()}
function closeModal(){const overlay=$('#modal');overlay.hidden=true;document.body.classList.remove('modal-open');$('#modal-content').innerHTML='';app.modalReturnFocus?.focus?.()}
function detailModal(id){const p=data.products.find(x=>x.id===id);if(!p)return;const imgs=p.images?.length?p.images:[fallback(p.short_name)];modal(`<div class="product-modal"><div><img id="modal-product-img" class="hero-product-image" src="${h(imgs[0])}" alt="${h(p.name)}"><div class="modal-subimages">${imgs.map((s,i)=>`<button data-modal-image="${h(s)}" class="${i===0?'active':''}" aria-label="Ver foto ${i+1}">${image('',s,'Foto '+(i+1))}</button>`).join('')}</div></div><div><p class="eyebrow red">${h(p.category)} / ${h(p.color||'PRETO')}</p><h2 class="display" id="modal-title">${h(p.short_name)}</h2><div class="price">${price(p.price_cents)}</div><p>${h(p.description||'')}</p><p>MATERIAL: ${h(p.material||'A confirmar')}</p><p class="small">Confira tamanhos, disponibilidade e preço final na loja original.</p>${onlyHTTP(p.url)?`<a href="${h(p.url)}" class="btn" target="_blank" rel="noopener noreferrer">COMPRAR NA LOJA ORIGINAL ↗</a>`:'<div class="admin-notice">Este produto não possui link de compra configurado.</div>'}</div></div>`)}
function formProduct(p=null){const catOptions=data.categories.map(v=>`<option ${p?.category===v?'selected':''}>${h(v)}</option>`).join('');const colOptions=data.collections.map(v=>`<option ${p?.collection===v?'selected':''}>${h(v)}</option>`).join('');modal(`<h2 class="modal-title display" id="modal-title">${p?'EDITAR':'ADICIONAR'} PRODUTO</h2><p class="muted">As alterações vão para o catálogo após salvar.</p><form id="product-form" data-id="${h(p?.id||'')}"><div class="form-grid"><div><label class="label">Nome do produto</label><input class="field" name="name" required maxlength="200" value="${h(p?.name||'')}"></div><div><label class="label">Nome curto no catálogo</label><input class="field" name="short_name" required maxlength="90" value="${h(p?.short_name||'')}"></div><div><label class="label">Preço (R$)</label><input class="field" name="price" type="number" step="0.01" min="0" max="999999" required value="${p?Number(p.price_cents)/100:''}"></div><div><label class="label">Cor</label><input class="field" name="color" value="${h(p?.color||'PRETO')}"></div><div><label class="label">Categoria</label><select class="select" name="category" required>${catOptions}</select></div><div><label class="label">Coleção</label><select class="select" name="collection" required>${colOptions}</select></div></div><label class="label">Descrição</label><textarea name="description" class="textarea">${h(p?.description||'')}</textarea><label class="label">Material / composição</label><textarea name="material" class="textarea">${h(p?.material||'')}</textarea><label class="label">Link para compra (HTTPS)</label><input class="field" name="url" type="url" value="${h(p?.url||'')}" placeholder="https://intactoz.com.br/products/..."><label class="label">Fotos (até 12 arquivos JPG, PNG ou WebP, máx. 5 MB cada)</label><input class="field" name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple><div class="image-preview" id="image-preview"></div><small class="muted">Fotos existentes permanecem até que você remova alguma. Em modo local as novas fotos são comprimidas para caber no navegador.</small><p class="form-feedback" id="product-feedback" role="status"></p><button class="btn" type="submit">SALVAR PRODUTO</button></form>`);app.editingImages=[...(p?.images||[])];renderImagePreviews()}
function renderImagePreviews(){$('#image-preview').innerHTML=(app.editingImages||[]).map((src,i)=>`<div>${image('',src,'Foto '+(i+1))}<button type="button" data-remove-image="${i}" aria-label="Remover foto ${i+1}">Remover</button>${i>0?`<button type="button" data-move-image="${i}" aria-label="Mover foto ${i+1} para a capa">↑ Capa</button>`:''}</div>`).join('')}
function taxModal(name=''){modal(`<h2 class="modal-title display" id="modal-title">${name?'EDITAR':'CRIAR'} ${app.adminTab==='categories'?'CATEGORIA':'COLEÇÃO'}</h2><form id="tax-form" data-original="${h(name)}"><label class="label" for="tax-name">Nome</label><input class="field" id="tax-name" name="name" maxlength="80" required value="${h(name)}"><p class="form-feedback" role="status" id="tax-feedback"></p><button class="btn" type="submit">SALVAR</button></form>`)}
async function compressImage(file){if(file.size>5*1024*1024)throw Error('Arquivo maior que 5 MB: '+file.name);if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Formato inválido: '+file.name);const bitmap=await createImageBitmap(file);const scale=Math.min(1,900/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error('Erro ao processar foto')),'image/webp',.76))}
function blobToDataURL(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Falha na leitura da imagem'));reader.readAsDataURL(blob)})}
async function uploadPhotos(files){const urls=[];for(const file of files){const compressed=await compressImage(file);if(supa){if(!isAdmin)throw Error('Acesso não autorizado');const filePath=`drops/${crypto.randomUUID()}.webp`;const {error}=await supa.storage.from('intactoz-products').upload(filePath,compressed,{contentType:'image/webp',cacheControl:'3600'});if(error)throw error;urls.push(supa.storage.from('intactoz-products').getPublicUrl(filePath).data.publicUrl)}else urls.push(await blobToDataURL(compressed))}return urls}
async function saveProduct(form){const fd=new FormData(form);const old=data.products.find(p=>p.id===form.dataset.id);const imgs=[...app.editingImages];const files=[...form.elements.photos.files];if(imgs.length+files.length>12)throw Error('Limite de 12 fotos por produto');const add=await uploadPhotos(files);const rec={id:old?.id||crypto.randomUUID(),name:fd.get('name').trim(),short_name:fd.get('short_name').trim(),price_cents:Math.round(Number(fd.get('price'))*100),color:fd.get('color').trim(),category:fd.get('category'),collection:fd.get('collection'),description:fd.get('description').trim(),material:fd.get('material').trim(),url:onlyHTTP(fd.get('url')),images:imgs.concat(add)};if(!rec.name||!rec.short_name||!Number.isFinite(rec.price_cents)||rec.price_cents<0)throw Error('Preencha os campos obrigatórios corretamente');if(fd.get('url')&&!rec.url)throw Error('Link de compra precisa começar com https://');if(supa){if(!isAdmin)throw Error('Sem permissão de administrador');const {error}=await supa.from('products').upsert(rec);if(error)throw error;await refreshData()}else{data.products=old?data.products.map(p=>p.id===old.id?rec:p):data.products.concat(rec);saveLocal()}}
async function removeProduct(id){const item=data.products.find(p=>p.id===id);if(!item||!confirm(`Remover ${item.name} do catálogo?`))return;try{if(supa){if(!isAdmin)throw Error('Sem permissão');const {error}=await supa.from('products').delete().eq('id',id);if(error)throw error;await refreshData()}else{data.products=data.products.filter(p=>p.id!==id);saveLocal()}toast('Produto removido');route()}catch(e){toast('Erro ao excluir: '+e.message)}}
async function saveTax(form){const value=String(new FormData(form).get('name')).trim(),old=form.dataset.original,tab=app.adminTab,col=tab==='categories'?'category':'collection';if(!value)throw Error('Nome é obrigatório');if(tab==='products')throw Error('Selecione uma seção');if(supa){if(!isAdmin)throw Error('Sem permissão');const table=tab;if(old){const {error}=await supa.from(table).update({name:value}).eq('name',old);if(error)throw error;if(old!==value){const {error:e2}=await supa.from('products').update({[col]:value}).eq(col,old);if(e2)throw e2}}else{const {error}=await supa.from(table).insert({name:value});if(error)throw error}await refreshData()}else{const list=tab==='categories'?data.categories:data.collections;if(old){const i=list.indexOf(old);if(i<0)throw Error('Item não encontrado');list[i]=value;data.products.forEach(p=>{if(p[col]===old)p[col]=value})}else if(!list.includes(value))list.push(value);saveLocal()}}
async function removeTax(name){const tab=app.adminTab,col=tab==='categories'?'category':'collection';if(data.products.some(p=>p[col]===name)){toast('Mova ou exclua os produtos desta categoria/coleção antes.');return}if(!confirm(`Remover ${name}?`))return;try{if(supa){const {error}=await supa.from(tab).delete().eq('name',name);if(error)throw error;await refreshData()}else{data[tab]=data[tab].filter(x=>x!==name);saveLocal()}toast('Item removido');route()}catch(e){toast('Erro: '+e.message)}}
async function submitAuth(form){const status=$('#auth-status');const fd=new FormData(form);const email=String(fd.get('email')).trim();const password=String(fd.get('password'));status.textContent='Aguarde…';try{if(app.authMode==='register'){const name=String(fd.get('name')||'').trim();const {error}=await supa.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:location.origin+location.pathname+'#/conta'}});if(error)throw error;status.textContent='Cadastro enviado! Confira seu e-mail para confirmar a conta, se a confirmação estiver ativada.'}else{const {error}=await supa.auth.signInWithPassword({email,password});if(error)throw error;await refreshAdmin();route()}}catch(e){status.textContent='Erro: '+e.message}}
}
function route(){const hash=location.hash.replace(/^#\/?/,'');const segments=hash.split('/');const section=segments[0]||'';const footer=$('#footer');main.innerHTML=section==='conta'?accountPage():section==='adm'?adminPage():homePage();footer.hidden=section==='adm';document.title=(section==='conta'?'Minha conta':section==='adm'?'Administração':'O under tem nome')+' — intactoz.';$('#header').classList.remove('nav-open');$('#menu-toggle').setAttribute('aria-expanded','false');if(['pecas','editorial','universo'].includes(section)){requestAnimationFrame(()=>document.getElementById(section)?.scrollIntoView())}else window.scrollTo(0,0);mountMotions()}
$('#menu-toggle').addEventListener('click',()=>{const open=$('#header').classList.toggle('nav-open');$('#menu-toggle').setAttribute('aria-expanded',String(open))});
window.addEventListener('hashchange',route);
main.addEventListener('click',async e=>{const cat=e.target.closest('[data-category]');if(cat){app.filter=cat.dataset.category;const pos=window.scrollY;route();window.scrollTo(0,pos);return}const detail=e.target.closest('[data-detail]');if(detail){detailModal(detail.dataset.detail);return}const auth=e.target.closest('[data-auth-mode]');if(auth){app.authMode=auth.dataset.authMode;route();return}if(e.target.closest('#logout')){if(supa)await supa.auth.signOut();user=null;isAdmin=false;route();return}if(e.target.closest('#reset-password')){const email=$('#auth-email')?.value?.trim();if(!email){toast('Digite seu e-mail primeiro.');return}const {error}=await supa.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname+'#/conta'});toast(error?'Erro: '+error.message:'Confira seu e-mail para redefinir a senha.');return}if(e.target.closest('#open-demo-admin')){app.demoAdmin=true;route();return}const tab=e.target.closest('[data-admin-tab]');if(tab){app.adminTab=tab.dataset.adminTab;app.adminQuery='';route();return}const add=e.target.closest('#add-new');if(add){app.adminTab==='products'?formProduct():taxModal();return}const edit=e.target.closest('[data-edit-product]');if(edit){formProduct(data.products.find(x=>x.id===edit.dataset.editProduct));return}const rm=e.target.closest('[data-remove-product]');if(rm){await removeProduct(rm.dataset.removeProduct);return}const taxEdit=e.target.closest('[data-edit-tax]');if(taxEdit){taxModal(taxEdit.dataset.editTax);return}const taxRm=e.target.closest('[data-remove-tax]');if(taxRm){await removeTax(taxRm.dataset.removeTax);return}});
main.addEventListener('change',e=>{if(e.target.id==='collection-filter'){app.collection=e.target.value;const y=window.scrollY;route();window.scrollTo(0,y)}});
main.addEventListener('input',e=>{if(e.target.id==='admin-search'){const focused=e.target;app.adminQuery=focused.value;$('#admin-list').innerHTML=adminList()}});
main.addEventListener('submit',async e=>{if(e.target.id==='auth-form'){e.preventDefault();if(supa)await submitAuth(e.target)}});
$('#modal').addEventListener('click',e=>{if(e.target.id==='modal'||e.target.closest('[data-close]')){closeModal();return}const imageButton=e.target.closest('[data-modal-image]');if(imageButton){$('#modal-product-img').src=imageButton.dataset.modalImage;$$('[data-modal-image]').forEach(b=>b.classList.toggle('active',b===imageButton));return}const remove=e.target.closest('[data-remove-image]');if(remove){app.editingImages.splice(Number(remove.dataset.removeImage),1);renderImagePreviews();return}const move=e.target.closest('[data-move-image]');if(move){const [img]=app.editingImages.splice(Number(move.dataset.moveImage),1);app.editingImages.unshift(img);renderImagePreviews()}});
$('#modal').addEventListener('submit',async e=>{if(!['product-form','tax-form'].includes(e.target.id))return;e.preventDefault();const form=e.target,btn=$('[type="submit"]',form);btn.disabled=true;try{if(form.id==='product-form')await saveProduct(form);else await saveTax(form);closeModal();toast('Alterações salvas');route()}catch(error){const sel=form.id==='product-form'?'#product-feedback':'#tax-feedback';$(sel,form).textContent='Erro: '+error.message}finally{btn.disabled=false}});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal').hidden)closeModal();if(e.key==='Tab'&&!$('#modal').hidden){const els=$$('a,button,input,select,textarea,[tabindex]:not([tabindex="-1"])',$('#modal')).filter(el=>!el.disabled);const i=els.indexOf(document.activeElement);if(e.shiftKey&&i===0){e.preventDefault();els.at(-1)?.focus()}else if(!e.shiftKey&&i===els.length-1){e.preventDefault();els[0]?.focus()}}});
document.addEventListener('error',e=>{const el=e.target;if(el instanceof HTMLImageElement&&el.dataset.fallback&&!el.dataset.hasFallback){el.dataset.hasFallback='1';el.src=fallback(el.dataset.fallback)}},true);
async function init(){main.innerHTML='<div class="page"><p class="eyebrow red">CARREGANDO O DROP...</p></div>';try{await setupBackend()}catch(err){console.error(err);toast('Falha ao carregar o catálogo.');data.products=structuredClone(initialProducts);data.categories=[...DEFAULT_CATEGORIES];data.collections=[...DEFAULT_COLLECTIONS]}route()}
init();
